version: '3'

volumes:
  pg_data_todo:

services:
  be:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASS: todo_pass
      REDIS_HOST: redis
      S3_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: XYZ
      AWS_SECRET_ACCESS_KEY: XYZ
      S3_BUCKET_NAME: test-bucket
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - pg_data_todo:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  gateway:
    build: ./gateway
    environment:
      PORT: 3030
      BE_HOST: be
      BE_PORT: 8000
      FE_HOST: be
      FE_PORT: 8000
    ports:
      - "3030:3030"
    depends_on:
      - be
