
# Gateway Configmap

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  nginx.conf: |
    events { }

    http {
      upstream frontend {
        server fe-service:{{ .Values.fe.service.port }};
      }

      upstream backend {
        server be-service:{{ .Values.be.service.port }};
      }

      server {
        listen {{ .Values.service.targetPort }};

        location / {
          proxy_pass http://frontend;
        }

        location /api/ {
          # Adding trailing slash to satisfy Django
          # Check if the request URI does not end with a slash
          if ($request_uri !~* /$) {
              # Add a trailing slash to the request URI
              rewrite ^(.*)$ $1/ break;
          }

          proxy_pass http://backend;
        }
      }
    }
