# Entry service config
service:
  type: NodePort
  port: 3030
  targetPort: 3030

# Gateway config
gateway:
  image:
    repository: nginx
    tag: stable-alpine3.19
  replicaCount: 1

# Frontend config
fe:
  service:
    type: ClusterIP
    port: 3050
    targetPort: 3050
  image:
    repository: public.ecr.aws/r5p6q2u1/js-example-spa
    tag: v1.0.3
  replicaCount: 1
  env:
    # Environment variables can also be passed here
    - name: ENABLE_CAPTCHA
      value: "false"
    - name: ALLOW_SIGNUP
      value: "false"

# Backend config
be:
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  image:
    repository: public.ecr.aws/r5p6q2u1/django-todo-be
    tag: 0.0.1
  replicaCount: 1
  env:
    # Environment variables can also be passed here
    - name: ENABLE_CAPTCHA
      value: "false"
    - name: ALLOW_SIGNUP
      value: "false"

# DB - Postgres values
postgresql:
  auth:
    username: todo_user
    password: todo_pass
    database: todo_db
  primary:
    service:
      port: 5432
    persistence:
      enabled: true
      size: 1Gi

# S3 config
s3:
  enabled: false
  bucket: django-todo-example-attachments
  region: ap-south-1
